### ISSUE TITLE
Upgrade to PostCSS 8

### ISSUE THREAD

**Issue by yangmingshan** [Genuifx/postcss-pxtorpx-pro#2]
It would be nice if this plugin can be upgrade to PostCSS 8 new API.

https://github.com/postcss/postcss/releases/tag/8.0.0

Related issue: https://github.com/cuth/postcss-pxtorem/issues/66

**Comment by Genuifx** [comment]
Make sense. I will update this plugin as soon as possible.

**Comment by Genuifx** [comment]
PostCSS 8: postcss-pxtorpx-pro@2.0.0-beta
